### ISSUE TITLE
Build Book error: `giveninits' undefined in families `blx@opt@pre'.

### ISSUE THREAD

**Issue by njtierney** [robjhyndman/MonashThesis#1]
Thanks for making this pkg available, Rob!

I get an error when I "build book" in RStudio - this is probably something to do with my machine, but perhaps you have an idea of what I could change to fix this?

Error message is:

```
output file: thesis.knit.md

! Package xkeyval Error: `giveninits' undefined in families `blx@opt@pre'.

Error: Failed to compile thesis.tex. See thesis.log for more info.
Execution halted

Exited with status 1.
```

Let me know if you need more info!

**Comment by robjhyndman** [comment]
You need to update your biblatex version. Or just update texlive.
