### ISSUE TITLE
How to reduce line space with the title?

### ISSUE THREAD

**Issue by dataandcrowd** [robjhyndman/MonashThesis#5]
I have a long title for my thesis. I rendered to a pdf but got too much vertical spaces. As an example, here is how it looks on my PDF:
```
The hydraulics of open channel flow: 


an introduction: basic principles, sediment motion, 


hydraulic modelling, design of


hydraulic structures
```

However, I want something like: 
```
The hydraulics of open channel flow: an introduction: basic principles, 
sediment motion, hydraulic modelling, design of hydraulic structures
```

Is there any way I can reduce the vertical lines?

**Comment by robjhyndman** [comment]
On line 189 of `monashthesis.cls` you will see this:

```tex
\Huge\textbf{\expandafter{\@title}}
```

Change `\Huge` to something like `\fontsize{16}{18}\selectfont`. Fiddle with the numbers until it looks right. The first number is the font size, the second is the line spacing.

**Comment by dataandcrowd** [comment]
Thank you so much. Problem Solved!
