### ISSUE TITLE
reduce space of codechunk

### ISSUE THREAD

**Issue by dataandcrowd** [robjhyndman/MonashThesis#6]
![code_chunk](https://user-images.githubusercontent.com/25252172/55102238-e276fa80-50bd-11e9-9e00-e5d60c52707f.PNG)

This is a my code chunk after compiling my work to a PDF, which is quite wide. Do you know I can reduce space in the chunk? Here is what my chunk actually looks like:
```
Family: gaussian 
Link function: identity 
Formula:
pm7_28 ~ s(X, Y, by = DEM) + s(DEM)
Parametric coefficients:
           Estimate   Std. Error   t value   Pr(>|t|)
(Intercept)     0          0          NA         NA
Approximate significance of smooth terms:
               edf    Ref.df      F       P-value    
s(X,Y):DEM  15.819   20.078   314.7    <0.0000002 ***
s(DEM)       1.001    1.001   601.5    <0.0000002 ***
--
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
Rank: 39/40
R-sq.(adj) =  0.672   Deviance explained =   76%
-REML = 187.95  Scale est. = 16.214    n = 60
```

**Comment by robjhyndman** [comment]
This is not a help site. Please ask Rmarkdown questions like this at https://community.rstudio.com/

**Comment by dataandcrowd** [comment]
> This is not a help site. Please ask Rmarkdown questions like this at https://community.rstudio.com/

Shame. I was quite stuck when I encountered some errors with your template, where the given files look very different to the files that original bookdown package offers. I will have a look at the community and figure out by myself. 
But I appreciate your endeavour on this template.
