### ISSUE TITLE
Figure captions and references in bold and italic

### ISSUE THREAD

**Issue by dataandcrowd** [robjhyndman/MonashThesis#7]
![figure_italic](https://user-images.githubusercontent.com/25252172/55102528-7cd73e00-50be-11e9-8239-50a47a0904f6.PNG)

Can I unbold my figure title and reference names? Also, can you help me deitalize my captions?

**Comment by robjhyndman** [comment]
Bold references suggest that latex has not completed, probably because an error was encountered first.
You can edit the monashthesis.cls file to change the style. Just search for captions.
