### ISSUE TITLE
Table of content Position

### ISSUE THREAD

**Issue by masiraji** [robjhyndman/MonashThesis#9]
Hello!
Thank you for providing such a handy way to create a reproducible thesis template.
I was trying to produce my thesis using this thesis temple, and facing some difficulty placing the table of content in the right place. I want to place it after the abstract. I looked into your detailed .cls file and tried to figure it out. However, was not able to find my path. Can you guide me here?

**Comment by robjhyndman** [comment]
It's included via the `\tighttoc` command here:
https://github.com/robjhyndman/MonashThesis/blob/7cc8e200c2f36c048d85200ddc3f8afc30958f0f/monashthesis.tex#L34

**Comment by masiraji** [comment]
Thank you for the reply. This may seem a naive question, how do I change the position of the toc. The new suggested format of Monash indicates abstract should come before TOC.

**Comment by robjhyndman** [comment]
Move that line to wherever you want it to go in the same file, or in one of the Rmd files.

**Comment by masiraji** [comment]
I have put the line in the Rmd file after which I wanted to start TOC. Worked like a charm. Thank you so much.
